# lek 295
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.17.0
          args: [
              "-p", # -p, --port <int>   Use port for clients (default: 4222)
              "4222",
              "-m", # -m, --http_port <int>  Use port for http monitoring
              "8222",
              "-hbi", # -hbi, --hb_interval <duration>   Interval at which server sends heartbeat to a client
              "5s",
              "-hbt", # -hbt, --hb_timeout <duration>   How long server waits for a heartbeat response
              "5s",
              "-hbf", # -hbf, --hb_fail_count <int>   Number of failed heartbeats before server closes the client connection
              "2",
              "-SD", # -SD, --stan_debug=<bool>   Enable STAN debugging output
              "-cid", # -cid, --cluster_id  <string>    Cluster ID (default: test-cluster)
              "next-ticket",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
